package NesteddTryCatchBlock;

public class try_cach {
	//main try_blick
	try {
		//try_block2
		try {
			//try_block3
			try {
				int arr[] = {1,2,3,4};
				System.out.print(arr[10]);
			} catch(ArithmeticEcewption e) { 
				System.out.print("Artimetic Exception");
				System.out.print("handled in try-block3");
			}
			
			catch(ArithmeticEcewption e) {
				System.out.print("Artimetic Exception");
				System.out.print("handled in try-block2");}
				catch(ArithmeticEcewption e3) {
					System.out.print("Artimetic Exception");
					System.out.print("handled in try-block");}
					catch (arrayindezoutofboundsexception e4){
					System.out.print("arrayindezoutofboundsexception");
					System.out.print("handled in try-block");}
								
					catch (Exception e5) {System.out.print("Exception");
					{System.out.print("Exceptoion");
					System.out.print("Iinside parent try catch block");}
					{System.out.prinln("next statement");}
					
					}
								
